/**
 * DK Holidays — Day-by-Day Itinerary Generation Engine
 * Creates structured, realistic day-by-day travel itineraries with:
 * - Timed Morning, Afternoon, and Evening activities
 * - Local culinary recommendations
 * - Daily insider tips & secret spots
 * - Budget breakdown per day
 */

import { DESTINATIONS } from '../data/destinations.js';

// Curated destination day templates
const ITINERARY_TEMPLATES = {
  manali: [
    {
      day: 1,
      title: 'Arrival, Cedar Woods & Old Manali Vibe',
      theme: 'Acclimatization & Mountain Culture',
      morning: {
        time: '09:00 AM – 12:00 PM',
        title: 'Walk Through Dhungri Pines & Hadimba Shrine',
        location: 'Hadimba Temple & Dhungri Forest',
        category: 'Heritage & Nature',
        desc: 'Begin your journey beneath centuries-old deodar trees. Explore the intricate 16th-century wooden pagoda temple carved from sacred cedar wood.',
        dining: 'Breakfast at Cafe 1947: Fresh apple cinnamon pancakes and mountain French press coffee.',
      },
      afternoon: {
        time: '01:30 PM – 04:30 PM',
        title: 'Old Manali Bohemian Lane & Art Cafes',
        location: 'Old Manali Village',
        category: 'Culture & Leisure',
        desc: 'Cross the bridge into cobblestone Old Manali. Browse handmade woolen craft shops, discover acoustic jazz cafes, and soak in the slow mountain pace.',
        dining: 'Lunch at Dylan’s Toasted & Roasted: Famous fresh chocolate walnut cookies and wood-fired trout.',
      },
      evening: {
        time: '06:00 PM – 08:30 PM',
        title: 'Riverside Sunset & Acoustic Fireplace Gathering',
        location: 'Manalsu River Stream',
        category: 'Relaxation',
        desc: 'Sit by the crystalline rushing mountain stream as dusk casts pink light over the Himalayan crests.',
        dining: 'Dinner at Drifters’ Cafe: Warm Siddu stuffed with poppy seeds and local walnut chutney.',
      },
      insiderTip: 'Take the narrow dirt trail behind Hadimba Temple toward Nasogi village for uncrowded apple orchard views with no vehicles.',
      estimatedCost: { stay: '₹4,000', food: '₹1,500', activities: '₹500', transport: '₹800' },
    },
    {
      day: 2,
      title: 'Solang Valley Heights & Jogini Waterfall Trek',
      theme: 'Alpine Adventure & Pristine Cascades',
      morning: {
        time: '08:30 AM – 12:30 PM',
        title: 'Tandem Paragliding & Solang Meadow Vistas',
        location: 'Solang Valley (13 km north)',
        category: 'High Adventure',
        desc: 'Ascend the Solang cable car to 3,200m for sweeping views of glaciers and jagged peaks, followed by thrilling paragliding flight.',
        dining: 'Mountain roadside chai with hot steamed momos and fresh mint chutney.',
      },
      afternoon: {
        time: '02:00 PM – 05:00 PM',
        title: 'Forest Hike to Sacred Jogini Waterfalls',
        location: 'Vashisht Village to Jogini Falls',
        category: 'Scenic Trail',
        desc: 'A gentle 3 km hike through apple orchards and pine groves ending at the multi-tiered cascades flowing from sacred cliffs.',
        dining: 'Late lunch in Vashisht: Israeli Shakshuka and herbal lemon-ginger tea.',
      },
      evening: {
        time: '06:30 PM – 08:30 PM',
        title: 'Natural Sulphur Hot Springs & Evening Soak',
        location: 'Vashisht Ancient Temple Baths',
        category: 'Wellness',
        desc: 'Soothe your muscles in the mineral-rich geothermal springs that have flowed naturally through stone tanks for millennia.',
        dining: 'Dinner at Il Forno: Authentic wood-fired Neapolitan pizza prepared in an Italian heritage kitchen.',
      },
      insiderTip: 'Start the Jogini hike before 2 PM to catch the afternoon sunlight illuminating the waterfall mist with rainbows.',
      estimatedCost: { stay: '₹4,000', food: '₹1,800', activities: '₹2,500', transport: '₹1,200' },
    },
    {
      day: 3,
      title: 'Atal Tunnel, Sissu Valley & Hidden Lahaul',
      theme: 'Trans-Himalayan Discovery',
      morning: {
        time: '07:30 AM – 11:30 AM',
        title: 'Cross the 9.02 km Atal Tunnel to Sissu Waterfall',
        location: 'Atal Tunnel & Sissu, Lahaul Valley',
        category: 'Trans-Himalayan',
        desc: 'Drive through the engineering marvel of Atal Tunnel to witness an instant transformation from lush Kullu valley into the dramatic stark terrain of Lahaul.',
        dining: 'Hot Thukpa soup and steaming butter tea at Sissu Lake Viewpoint cafe.',
      },
      afternoon: {
        time: '01:00 PM – 04:00 PM',
        title: 'Sissu Lake Exploration & Willow Groves',
        location: 'Chandra River Basin',
        category: 'Nature & Photography',
        desc: 'Stroll around the shimmering alpine lake framed by towering glacial waterfalls plunging over sheer granite walls.',
        dining: 'Picnic lunch with local Tibetan tingmo bread and mountain lentil curry.',
      },
      evening: {
        time: '05:30 PM – 08:00 PM',
        title: 'Return to Manali & Bonfire Gathering',
        location: 'Cedar Lodge',
        category: 'Leisure',
        desc: 'Drive back through the tunnel as twilight blankets the Pir Panjal mountains; unwind by a crackling cedar fire.',
        dining: 'Dinner at The Lazy Dog: Grilled Himalayan rainbow trout and spiced mulled cider.',
      },
      insiderTip: 'Check weather conditions in Lahaul before departing early; morning road visibility is crispest between 8 AM and 11 AM.',
      estimatedCost: { stay: '₹4,000', food: '₹1,600', activities: '₹1,000', transport: '₹2,500' },
    },
    {
      day: 4,
      title: 'Naggar Castle & Heritage Art Trails',
      theme: 'Royal Art & Ancient Architecture',
      morning: {
        time: '09:30 AM – 12:30 PM',
        title: 'Medieval Naggar Castle Exploration',
        location: 'Naggar Village (21 km south)',
        category: 'Heritage',
        desc: 'Tour the 500-year-old wooden castle built with earthquake-resistant Kathkuni architectural techniques, perched high above the Beas River.',
        dining: 'Traditional apple pie and mountain coffee in the castle courtyard cafe.',
      },
      afternoon: {
        time: '01:30 PM – 04:30 PM',
        title: 'Nicholas Roerich Art Gallery & Estate',
        location: 'Roerich Estate, Naggar',
        category: 'Art & Heritage',
        desc: 'Step into the preserved studio of famed Russian mystic painter Nicholas Roerich, who painted thousands of Himalayan spiritual canvases.',
        dining: 'Lunch at Nightingale: Wood-smoked trout and local plum crumble.',
      },
      evening: {
        time: '06:00 PM – 08:30 PM',
        title: 'Local Souvenir Hunt & Pure Wool Looms',
        location: 'Naggar & Mall Road Artisans',
        category: 'Shopping & Craft',
        desc: 'Meet local weavers crafting pure Kullu shawls, handmade deodar honey, and artisanal apple preserves to bring home.',
        dining: 'Farewell dinner at Chopsticks: Authentic Tibetan momos and hot sweet ginger tea.',
      },
      insiderTip: 'The upper wooden balcony of Naggar Castle provides a panoramic 180-degree view of snow peaks with practically no crowds before 11 AM.',
      estimatedCost: { stay: '₹4,000', food: '₹1,400', activities: '₹600', transport: '₹1,500' },
    },
    {
      day: 5,
      title: 'Sethan Village & Dome Stargazing',
      theme: 'High Altitude Serenity',
      morning: {
        time: '10:00 AM – 01:00 PM',
        title: '4x4 Climb to Sethan Igloo & Geodesic Domes',
        location: 'Sethan Valley (2,700m)',
        category: 'High Altitude',
        desc: 'Ascend 35 steep hairpin curves to this tiny Buddhist horse-herder settlement overlooking the whole Kullu valley below.',
        dining: 'Mountain herbal tea with freshly baked buckwheat bread.',
      },
      afternoon: {
        time: '02:00 PM – 05:00 PM',
        title: 'Hampta Pass Base Trek & Bouldering',
        location: 'Pandu Ropa Meadows',
        category: 'Alpine Hike',
        desc: 'Trek along alpine meadow paths carpeted in wild mountain flora with dramatic vistas of Indrasan and Deo Tibba peaks.',
        dining: 'Hearty camp lunch with warm dal, organic mountain spinach, and steamed rice.',
      },
      evening: {
        time: '06:30 PM – 09:30 PM',
        title: 'Stargazing Under Zero-Pollution Skies',
        location: 'Sethan Dome Observation Deck',
        category: 'Astronomy & Romance',
        desc: 'Watch the Milky Way arch over snow peaks in one of India’s clearest high-altitude dark sky sanctuaries.',
        dining: 'Starlight dinner around campfire with warm soups and roasted kebabs.',
      },
      insiderTip: 'Bring warm thermal layers even in early summer; Sethan temperatures drop sharply once the sun dips behind the ridge.',
      estimatedCost: { stay: '₹5,500', food: '₹1,800', activities: '₹1,200', transport: '₹2,000' },
    },
  ],
  coorg: [
    {
      day: 1,
      title: 'Misty Plantation Welcome & Abbey Waterfalls',
      theme: 'Plantation Living & Waterfalls',
      morning: {
        time: '09:00 AM – 12:00 PM',
        title: 'Estate Walk & Private Coffee Cupping',
        location: 'Private Coffee Plantation Estate',
        category: 'Coffee & Nature',
        desc: 'Walk beneath canopy trees sheltering Arabica and Robusta plants. Learn how shade-grown coffee, pepper vines, and cardamom are harvested.',
        dining: 'Freshly brewed estate coffee with traditional Akki Roti and melted homemade butter.',
      },
      afternoon: {
        time: '01:30 PM – 04:30 PM',
        title: 'Abbey Falls Hanging Bridge Exploration',
        location: 'Abbey Falls (8 km from Madikeri)',
        category: 'Scenic Nature',
        desc: 'Walk along a paved spice path down to the roaring waterfall cascading into the Kaveri river basin from a hanging bridge.',
        dining: 'Lunch at Raintree Restaurant: Spiced mushroom pepper fry, rice dumplings, and tender bamboo shoot curry.',
      },
      evening: {
        time: '05:30 PM – 07:30 PM',
        title: 'Sunset Panorama at Raja’s Seat',
        location: 'Raja’s Seat Viewpoint',
        category: 'Sunset & Heritage',
        desc: 'Watch the sun dip below misty Western Ghats horizons from the royal garden pavilion once favored by Kodagu kings.',
        dining: 'Dinner at Taste of Coorg: Authentic Kadambuttu (steamed rice balls) with fragrant Coorg gravy.',
      },
      insiderTip: 'Visit Abbey Falls between 1 PM and 3 PM when midday sun cuts through the dense forest canopy, offering the clearest light for photography.',
      estimatedCost: { stay: '₹4,500', food: '₹1,600', activities: '₹400', transport: '₹1,000' },
    },
    {
      day: 2,
      title: 'Tadiandamol Shola Hike & Chelavara Falls',
      theme: 'Western Ghats Summit & Secret Streams',
      morning: {
        time: '07:00 AM – 12:30 PM',
        title: 'Trek to Tadiandamol Peak (Coorg’s Highest Summit)',
        location: 'Kakkabe & Tadiandamol Trail (1,748m)',
        category: 'Hiking & Adventure',
        desc: 'Hike through Shola grasslands and dense rainforest ribbons to reach the highest point in Kodagu with views rolling into Kerala.',
        dining: 'Packed trail breakfast: Boiled country eggs, energy nuts, and hot thermos coffee.',
      },
      afternoon: {
        time: '02:00 PM – 04:30 PM',
        title: 'Chelavara Waterfall Natural Basin',
        location: 'Chelavara (Tortoise Rock)',
        category: 'Hidden Gems',
        desc: 'A natural waterfall shaped like a tortoise shell nestled amongst private coffee estates, away from the tourist rush.',
        dining: 'Late lunch at a traditional planter’s homestay: Wild mango curry and steaming brown rice.',
      },
      evening: {
        time: '06:00 PM – 08:30 PM',
        title: 'Plantation Fireplace & Spice Tasting',
        location: 'Estate Verandah',
        category: 'Relaxation',
        desc: 'Unwind on wide wooden armchairs with the evening symphony of cicadas, sampling roasted estate coffee and spiced cocoa.',
        dining: 'Dinner at The Fort Mercara: Pepper chicken or Jackfruit curry with fragrant jeera rice.',
      },
      insiderTip: 'Start the Tadiandamol hike by 7:30 AM to ascend before the afternoon mist sweeps in and obscures the summit panoramic view.',
      estimatedCost: { stay: '₹4,500', food: '₹1,800', activities: '₹800', transport: '₹1,400' },
    },
    {
      day: 3,
      title: 'Tibetan Golden Temple & Dubare Elephant Camp',
      theme: 'Spiritual Peace & Wildlife',
      morning: {
        time: '08:30 AM – 11:30 AM',
        title: 'Dubare Elephant Camp on the Kaveri River',
        location: 'Dubare Forest Sanctuary',
        category: 'Wildlife & Nature',
        desc: 'Cross the Kaveri River by wooden boat to observe elephants being groomed and fed in their natural riparian forest habitat.',
        dining: 'South Indian filter coffee with crisp medu vada and fresh coconut chutney.',
      },
      afternoon: {
        time: '01:00 PM – 04:00 PM',
        title: 'Namdroling Golden Temple in Bylakuppe',
        location: 'Bylakuppe Tibetan Settlement',
        category: 'Cultural Heritage',
        desc: 'Enter an astonishing realm of gilded 40-foot Buddha statues, prayer wheels, and resonant monk chants inside the monastery.',
        dining: 'Lunch at Tibetan Kitchen: Hand-pulled Thukpa noodles and steamed vegetable momos.',
      },
      evening: {
        time: '05:30 PM – 08:00 PM',
        title: 'Artisanal Coorg Spice & Homemade Chocolate Shopping',
        location: 'Madikeri Heritage Market',
        category: 'Shopping',
        desc: 'Stock up on farm-fresh green cardamom, Malabar black pepper, single-origin Arabica beans, and artisanal dark chocolates.',
        dining: 'Farewell dinner at East End: Coorg mutton dry fry or paneer ghee roast with Neer Dosa.',
      },
      insiderTip: 'Attend the 1:00 PM monastic prayer session at Namdroling Monastery to hear the deep overtones of traditional Tibetan horns and bells.',
      estimatedCost: { stay: '₹4,500', food: '₹1,500', activities: '₹600', transport: '₹1,200' },
    },
  ],
  'swiss-alps': [
    {
      day: 1,
      title: 'Arrival in Zermatt & Iconic Matterhorn Views',
      theme: 'Alpine Magic & Glacial Air',
      morning: {
        time: '09:00 AM – 12:00 PM',
        title: 'Gornergrat Cogwheel Train to 3,089m',
        location: 'Gornergrat Railway, Zermatt',
        category: 'Scenic Alpine Train',
        desc: 'Ride Europe’s highest open-air cogwheel railway across stone viaducts to reach Gornergrat, facing 29 four-thousand-meter peaks.',
        dining: 'Hot Swiss cocoa and warm buttery croissants at 3100 Kulmhotel Gornergrat.',
      },
      afternoon: {
        time: '01:30 PM – 04:30 PM',
        title: 'Riffelsee Mirror Lake Hike',
        location: 'Riffelsee (2,757m)',
        category: 'Alpine Hike',
        desc: 'A gentle 45-minute alpine walk to the crystal-clear glacial tarn that reflects the symmetrical pyramid of the Matterhorn on its still surface.',
        dining: 'Lunch at Alphitta: Traditional crispy Rösti topped with Gruyère cheese and a farm-fresh egg.',
      },
      evening: {
        time: '06:00 PM – 08:30 PM',
        title: 'Stroll Car-Free Zermatt Old Village (Hinterdorf)',
        location: 'Zermatt Hinterdorfstrasse',
        category: 'Heritage',
        desc: 'Wander past 500-year-old larch-wood barns and chalets resting on stone discs that kept alpine mice away.',
        dining: 'Dinner at Chez Vrony: Legendary organic hay-soup and artisanal cheese fondue.',
      },
      insiderTip: 'Take the Gornergrat train on the right-hand side going up for the most dramatic Matterhorn window views during the ascent.',
      estimatedCost: { stay: '€220', food: '€70', activities: '€95', transport: '€40' },
    },
    {
      day: 2,
      title: 'Glacier Express & Lauterbrunnen Waterfalls',
      theme: 'Postcard Villages & Rail Odyssey',
      morning: {
        time: '08:30 AM – 12:00 PM',
        title: 'Panoramic Rail Through Alpine Gorges',
        location: 'Valais to Bernese Oberland',
        category: 'Scenic Train',
        desc: 'Travel in glass-domed panoramic carriages winding past cascading mountain streams, snowfields, and picturesque wooden chalets.',
        dining: 'On-board three-course Swiss lunch with regional Valais wine.',
      },
      afternoon: {
        time: '01:30 PM – 05:00 PM',
        title: 'Lauterbrunnen Valley of 72 Waterfalls & Staubbach',
        location: 'Lauterbrunnen Valley',
        category: 'Nature & Scenery',
        desc: 'Explore the sheer vertical limestone valley where Staubbach Falls plunges nearly 300 meters into misty air.',
        dining: 'Afternoon tea with freshly baked apple strudel and vanilla custard.',
      },
      evening: {
        time: '06:30 PM – 09:00 PM',
        title: 'Swiss Raclette by Chalet Fireplace',
        location: 'Wengen Chalet Village',
        category: 'Culinary & Romance',
        desc: 'Unwind in a high-perched car-free village overlooking the twilight-lit Lauterbrunnen valley.',
        dining: 'Traditional scraped raclette cheese served over baby potatoes and pearl onions.',
      },
      insiderTip: 'Take the interior cliff tunnel at Trümmelbach Falls to witness ten subterranean glacial waterfalls roaring inside the mountain.',
      estimatedCost: { stay: '€210', food: '€65', activities: '€35', transport: '€55' },
    },
    {
      day: 3,
      title: 'Lake Oeschinen Turquoise Rowboats & Alpine Spas',
      theme: 'Glacial Jewels & Alpine Wellness',
      morning: {
        time: '09:00 AM – 12:30 PM',
        title: 'Gondola to Lake Oeschinen & Rowboat Drift',
        location: 'Kandersteg, UNESCO World Heritage',
        category: 'Glacial Lake',
        desc: 'Glaze across the turquoise glacial jewel surrounded by 500-meter vertical cliffs with melted snow cascades feeding the water.',
        dining: 'Fresh mountain berry tart and herbal Swiss Alpine tea.',
      },
      afternoon: {
        time: '02:00 PM – 05:00 PM',
        title: 'Alpine Panorama Trail & Toboggan Run',
        location: 'Oeschinensee Mountain Coaster',
        category: 'Fun & Scenic',
        desc: 'Hike the higher panoramic loop above the lake or zoom down the 750-meter alpine mountain coaster with mountain vistas.',
        dining: 'Lakeside picnic with Swiss Gruyère, cured bresaola, and dark rye bread.',
      },
      evening: {
        time: '06:30 PM – 08:30 PM',
        title: 'Thermal Baths Soak Facing Snow Peaks',
        location: 'Leukerbad or Alpine Spa Resort',
        category: 'Wellness',
        desc: 'Submerge in naturally heated mineral waters (36°C) while breathing in crisp mountain air under the stars.',
        dining: 'Candlelight dinner at Hotel Schweizerhof: Pan-seared trout and chocolate fondue.',
      },
      insiderTip: 'Rent a wooden rowboat at Oeschinensee between 10 AM and 11:30 AM before afternoon winds create ripples on the glass surface.',
      estimatedCost: { stay: '€240', food: '€75', activities: '€45', transport: '€30' },
    },
  ],
  bali: [
    {
      day: 1,
      title: 'Ubud Emerald Terraces & Sacred Forests',
      theme: 'Cultural Heartland & Tropical Green',
      morning: {
        time: '08:00 AM – 11:30 AM',
        title: 'Sunrise Walk at Tegallalang Rice Terraces',
        location: 'Tegallalang Valley, Ubud',
        category: 'Nature & Photography',
        desc: 'Wander along the intricate stepped terraces before the crowds arrive. Watch the morning sunbeams illuminate palm fronds and dew on the rice paddies.',
        dining: 'Breakfast at Tis Cafe: Pitaya dragonfruit smoothie bowl and freshly pressed coconut water.',
      },
      afternoon: {
        time: '01:00 PM – 04:00 PM',
        title: 'Sacred Monkey Forest & Saraswati Lotus Temple',
        location: 'Central Ubud',
        category: 'Heritage & Wildlife',
        desc: 'Explore moss-covered stone carvings under giant banyan trees inhabited by long-tailed macaques, followed by the water palace of Saraswati.',
        dining: 'Lunch at Clear Cafe: Balinese vegetable curry and cashew-nut mylk.',
      },
      evening: {
        time: '05:30 PM – 08:30 PM',
        title: 'Campuhan Ridge Walk & Organic Dining',
        location: 'Campuhan River Ridge',
        category: 'Sunset Walk',
        desc: 'Stroll the scenic hill trail flanked by two river valleys as the sky turns apricot and lavender.',
        dining: 'Dinner at Locavore NXT or Bebek Bengil (Dirty Duck Diner): Crispy spiced duck with sambal matah.',
      },
      insiderTip: 'Walk past the commercial front of Tegallalang terraces to the far northern ridge where local farmers still offer fresh young coconuts for a few rupiah.',
      estimatedCost: { stay: '$90', food: '$30', activities: '$20', transport: '$25' },
    },
    {
      day: 2,
      title: 'Water Purification & Mount Batur Volcano',
      theme: 'Spiritual Ceremonies & Volcanic Ridges',
      morning: {
        time: '05:00 AM – 10:30 AM',
        title: 'Mount Batur Sunrise Jeep Tour & Caldera Lake',
        location: 'Kintamani Highland',
        category: 'Volcano & Sunrise',
        desc: 'Watch the sunrise over Mount Agung and Lake Batur from the volcanic black lava fields in an open-top 4x4 vintage jeep.',
        dining: 'Steaming banana pancakes and Balinese Kopi Tubruk coffee cooked over volcanic vents.',
      },
      afternoon: {
        time: '01:00 PM – 04:00 PM',
        title: 'Melukat Sacred Water Cleansing at Tirta Empul',
        location: 'Tirta Empul Temple, Tampaksiring',
        category: 'Spiritual Ritual',
        desc: 'Partake in the ancient Balinese purification ritual at the sacred spring pools where natural mountain waters bubble from the earth.',
        dining: 'Lunch at Sari Organik: Farm-to-table organic Nasi Campur overlooking duck ponds.',
      },
      evening: {
        time: '06:00 PM – 08:30 PM',
        title: 'Traditional Legong Dance at Ubud Palace',
        location: 'Puri Saren Agung (Ubud Palace)',
        category: 'Cultural Performance',
        desc: 'Witness the mesmerizing Gamelan orchestra and intricate eye-and-finger choreography of classical Balinese dancers in a royal courtyard.',
        dining: 'Dinner at Indus Restaurant: Sunset cocktail and fragrant beef rendang overlooking the Tjampuhan valley.',
      },
      insiderTip: 'Wear a traditional sarong and sash at Tirta Empul; modest attire is respectfully required to enter the holy water spouts.',
      estimatedCost: { stay: '$90', food: '$35', activities: '$40', transport: '$30' },
    },
    {
      day: 3,
      title: 'Uluwatu Clifftops, Kecak Fire Dance & Beach Cove',
      theme: 'Coastal Drama & Ocean Sunset',
      morning: {
        time: '09:30 AM – 01:00 PM',
        title: 'Hidden Cove Swim at Padang Padang or Bingin Beach',
        location: 'Bukit Peninsula Coast',
        category: 'Beach & Waves',
        desc: 'Descend through limestone caves to reach turquoise wave coves beloved by surfers, framed by tropical cliffs.',
        dining: 'Beach shack lunch: Freshly grilled mahi-mahi with garlic lime butter and chilled Bintang.',
      },
      afternoon: {
        time: '03:00 PM – 05:30 PM',
        title: 'Uluwatu Clifftop Temple Walk',
        location: 'Pura Luhur Uluwatu (70m cliff)',
        category: 'Temple & Ocean',
        desc: 'Walk the dramatic coastal ramparts built directly on the precipice where Indian Ocean rollers crash against sheer limestone.',
        dining: 'Chilled dragonfruit juice at Single Fin clifftop bar.',
      },
      evening: {
        time: '06:00 PM – 08:30 PM',
        title: 'Sunset Kecak & Fire Dance over the Ocean',
        location: 'Uluwatu Amphitheatre',
        category: 'Iconic Spectacle',
        desc: 'Seventy chanting men form concentric circles singing the hypnotic "Chak-a-chak" rhythm as the sun sinks into the sea behind the fire ring.',
        dining: 'Candlelight seafood feast on the sand at Jimbaran Bay: King prawns, squid, and grilled red snapper.',
      },
      insiderTip: 'Arrive at the Uluwatu amphitheatre by 5:15 PM to get middle-tier seats for the most dramatic angle aligning the sunset behind the dancers.',
      estimatedCost: { stay: '$110', food: '$45', activities: '$25', transport: '$35' },
    },
  ],
  ladakh: [
    {
      day: 1,
      title: 'Acclimatization, Leh Palace & Shanti Stupa',
      theme: 'High-Altitude Rest & Stupa Sunsets',
      morning: {
        time: '09:00 AM – 12:00 PM',
        title: 'Gentle Acclimatization & Leh Heritage Old Town',
        location: 'Leh Bazaar & Tibetan Market (3,500m)',
        category: 'Acclimatization',
        desc: 'Drink plenty of water and take gentle slow steps. Browse Tibetan prayer wheels, pashmina shawls, and lapis lazuli jewelry.',
        dining: 'Warm Butter Tea (Gur Gur Chai) with freshly baked Ladakhi Khambir bread.',
      },
      afternoon: {
        time: '01:30 PM – 04:30 PM',
        title: 'Leh Palace Heritage Exploration',
        location: 'Namgyal Hill, Leh',
        category: 'Royal Heritage',
        desc: 'Tour the 17th-century 9-storey royal palace modeled after Tibet’s Potala Palace, commanding panoramic views over the Stok Kangri range.',
        dining: 'Lunch at Gesmo Restaurant: Warm yak-cheese pizza and apricot juice.',
      },
      evening: {
        time: '05:30 PM – 07:30 PM',
        title: 'Sunset at White Shanti Stupa',
        location: 'Changsps, Shanti Stupa',
        category: 'Spiritual Sunset',
        desc: 'Climb the white dome stupa inaugurated by the 14th Dalai Lama as golden sunset light washes across the Indus River valley.',
        dining: 'Dinner at Bon Appetit: Wood-roasted lamb chops and hot mountain vegetable soup.',
      },
      insiderTip: 'Strict medical rule: Rest completely in bed for the first 24 hours in Leh without rushing to any high passes to allow red blood cells to adapt.',
      estimatedCost: { stay: '₹5,000', food: '₹1,500', activities: '₹300', transport: '₹700' },
    },
    {
      day: 2,
      title: 'Thiksey Monastery & Hemis Monastic Treasury',
      theme: 'Ancient Gompas & Monk Chants',
      morning: {
        time: '06:00 AM – 10:30 AM',
        title: 'Dawn Chanting Prayers at Thiksey Monastery',
        location: 'Thiksey Gompa (19 km east of Leh)',
        category: 'Buddhist Heritage',
        desc: 'Climb through the 12 levels of the cliff monastery at sunrise to hear the deep conch shells, drums, and young monks chanting in the prayer hall.',
        dining: 'Monastery cafe breakfast: Steamed tingmo buns and hot saffron Kahwa tea.',
      },
      afternoon: {
        time: '12:00 PM – 04:00 PM',
        title: 'Shey Palace & Giant Copper Buddha',
        location: 'Shey & Hemis Sanctuary',
        category: 'Heritage',
        desc: 'Explore the summer capital of Ladakh housing a massive 12-meter gold-plated copper statue of Shakyamuni Buddha.',
        dining: 'Lunch at The Tibetan Kitchen: Steamed mutton momos and hot Thukpa soup.',
      },
      evening: {
        time: '05:30 PM – 08:00 PM',
        title: 'Sindhu Ghat River Walk & Evening Calm',
        location: 'Indus Riverbank (Sindhu Ghat)',
        category: 'Nature',
        desc: 'Sit beside the sacred Indus River flowing between cold desert mountains under deep indigo skies.',
        dining: 'Dinner at Lamayuru Restaurant: Ladakhi Skyu (hand-rolled pasta stew with vegetables).',
      },
      insiderTip: 'Stand respectfully at the back of the Thiksey prayer hall during morning puja; monks often offer hot butter tea to visitors after chants finish.',
      estimatedCost: { stay: '₹5,000', food: '₹1,400', activities: '₹500', transport: '₹1,800' },
    },
    {
      day: 3,
      title: 'Pangong Tso Cobalt Waters & Chang La Pass',
      theme: 'The Infinite High-Altitude Lake',
      morning: {
        time: '06:30 AM – 12:00 PM',
        title: 'Conquer Chang La Pass (5,360m) to Pangong Lake',
        location: 'Chang La Mountain Pass',
        category: 'High Altitude Pass',
        desc: 'Drive across the world’s third-highest motorable pass with prayer flags whipping in the mountain gale, descending into the turquoise realm of Pangong.',
        dining: 'Hot Maggi and ginger tea at Chang La Army cafe outpost.',
      },
      afternoon: {
        time: '01:00 PM – 05:00 PM',
        title: 'Pangong Tso Shifting Colors Walk',
        location: 'Lukung & Spangmik (4,250m)',
        category: 'Lake Wonder',
        desc: 'Stroll along the pebble shores of the 134-km long saltwater lake, watching its shades shift between emerald, turquoise, and deep cobalt blue.',
        dining: 'Camp lunch with fresh dal, roti, and warm sabzi.',
      },
      evening: {
        time: '06:30 PM – 09:30 PM',
        title: 'Stargazing the Milky Way & Luxury Glamping',
        location: 'Spangmik Glamping Camps',
        category: 'Astronomy Wonder',
        desc: 'Witness billions of stars and the vivid spine of the Milky Way reflected in the dark lake under zero light pollution.',
        dining: 'Campfire dinner with warm soups and Ladakhi walnut dessert.',
      },
      insiderTip: 'Dress in 3 to 4 thermal layers; night temperatures at Pangong drop below freezing even in peak July and August.',
      estimatedCost: { stay: '₹6,500', food: '₹1,800', activities: '₹400', transport: '₹4,500' },
    },
  ],
  munnar: [
    {
      day: 1,
      title: 'Emerald Tea Gardens, Mattupetty & Echo Point',
      theme: 'Endless Green & Highland Lakes',
      morning: {
        time: '09:00 AM – 12:30 PM',
        title: 'Walk Through KDHP Tea Plantations & Factory Tour',
        location: 'Nullatanni Estate & Tea Museum',
        category: 'Tea Heritage',
        desc: 'Walk along manicured green terraces. Learn the art of orthodox black tea plucking, withering, and processing followed by a professional tea tasting.',
        dining: 'Tea Museum Cafe: Warm cardamom-spiced tea with fresh hot banana fritters (Pazham Pori).',
      },
      afternoon: {
        time: '01:30 PM – 04:30 PM',
        title: 'Speedboat Ride on Mattupetty Dam Reservoir',
        location: 'Mattupetty Lake & Hills',
        category: 'Boating & Scenery',
        desc: 'Glide past rolling hills and dense eucalyptus forests where wild Asian elephant herds frequently come to drink at the water’s edge.',
        dining: 'Lunch at Saravana Bhavan: Traditional Kerala meal served on a fresh banana leaf with sambar and payasam.',
      },
      evening: {
        time: '05:30 PM – 07:30 PM',
        title: 'Echo Point Screams & Kundala Dam Sunbeams',
        location: 'Echo Point & Kundala Lake',
        category: 'Scenic Fun',
        desc: 'Call out over the mist-covered lake to hear natural acoustic reverberations bouncing between the surrounding mountain walls.',
        dining: 'Dinner at Rapsy Restaurant: Malabar chicken/paneer roast with flaky coin parottas.',
      },
      insiderTip: 'Stop at Photo Point at 10 AM when sunlight creates stunning chiaroscuro contrast between the dark tea leaves and drifting morning mist.',
      estimatedCost: { stay: '₹3,800', food: '₹1,200', activities: '₹700', transport: '₹1,000' },
    },
    {
      day: 2,
      title: 'Eravikulam National Park & Nilgiri Tahr Sanctuary',
      theme: 'High Peaks & Endangered Wildlife',
      morning: {
        time: '07:30 AM – 11:30 AM',
        title: 'Safari Through Eravikulam & View of Anamudi Peak',
        location: 'Rajamalai, Eravikulam National Park',
        category: 'Wildlife & Flora',
        desc: 'Board the eco-park bus winding into high shola grasslands to see the rare mountain goats (Nilgiri Tahr) grazing peacefully against Anamudi Peak (2,695m).',
        dining: 'Park cafe: Spiced buttermilk and steamed idlis with fresh mint chutney.',
      },
      afternoon: {
        time: '01:00 PM – 04:00 PM',
        title: 'Attukad Waterfalls Jungle Trail',
        location: 'Pallivasal / Attukad Valley',
        category: 'Waterfalls & Jungle',
        desc: 'Cross a historic narrow bridge to reach this dramatic multi-tiered cascade surrounded by lush cardamom hills and wild ferns.',
        dining: 'Lunch at Farmyard Restaurant: Kerala vegetable stew with soft appams.',
      },
      evening: {
        time: '05:30 PM – 08:30 PM',
        title: 'Ayurvedic Herbal Rejuvenation Massage',
        location: 'Heritage Ayurveda Centre',
        category: 'Wellness & Spa',
        desc: 'Experience authentic Abhyanga warm herbal oil massage to deeply soothe your muscles after mountain hiking.',
        dining: 'Dinner at Copper Castle: Grilled pepper fish or vegetable kurma with rice.',
      },
      insiderTip: 'Book Eravikulam safari slots online 3 days in advance to skip the 1-hour ticket queue at the highway entry gate.',
      estimatedCost: { stay: '₹3,800', food: '₹1,400', activities: '₹1,800', transport: '₹1,100' },
    },
    {
      day: 3,
      title: 'Kolukkumalai Sunrise Above Clouds & Spice Gardens',
      theme: 'The Cloud Inversion Epic',
      morning: {
        time: '04:30 AM – 09:30 AM',
        title: '4x4 Jeep Safari to Kolukkumalai Sunrise (2,160m)',
        location: 'Kolukkumalai Tea Estate (Highest in the world)',
        category: 'Epic Sunrise',
        desc: 'Rumble up rugged boulder paths in a vintage 4x4 jeep in pitch blackness to witness the dawn break over an endless ocean of rolling clouds.',
        dining: 'Fresh orthodox tea brewed on the peak with freshly baked ginger biscuits.',
      },
      afternoon: {
        time: '12:00 PM – 03:30 PM',
        title: 'Organic Spice Plantation & Treehouse Walk',
        location: 'Chithirapuram Spice Valley',
        category: 'Spices & Flora',
        desc: 'Smell fresh nutmeg, cloves, green cardamom pods on the vine, and cinnamon bark during a guided walk with a botanist.',
        dining: 'Lunch at Salkara: Malabar biryani with cool cucumber raita and date pickle.',
      },
      evening: {
        time: '05:00 PM – 07:30 PM',
        title: 'Kalaripayattu Martial Arts & Kathakali Performance',
        location: 'Punnamada Cultural Centre, Munnar',
        category: 'Kerala Heritage',
        desc: 'Watch the ancient Kerala martial art featuring flaming swords and leaping combat, followed by expressive classical Kathakali storytelling.',
        dining: 'Farewell dinner at Guru’s: Kerala thali with fresh coconut payasam dessert.',
      },
      insiderTip: 'Hold on tight during the Kolukkumalai jeep ride—it is famously bumpy, but the view of the sunrise above the cloud ocean is once-in-a-lifetime.',
      estimatedCost: { stay: '₹3,800', food: '₹1,500', activities: '₹2,500', transport: '₹2,000' },
    },
  ],
};

/**
 * Generate a complete, tailored day-by-day itinerary
 */
export function generateItinerary({
  destinationId = 'manali',
  durationDays = 4,
  travelStyle = 'balanced',
  budgetTier = 'balanced',
  groupType = 'couple',
  customPreferences = [],
}) {
  const dest = DESTINATIONS.find((d) => d.id === destinationId);
  const destinationName = dest ? dest.name : (destinationId.charAt(0).toUpperCase() + destinationId.slice(1).replace('-', ' '));

  let baseTemplates = ITINERARY_TEMPLATES[destinationId];

  // Alias support (e.g. zermatt -> swiss-alps)
  if (!baseTemplates && destinationId === 'zermatt') {
    baseTemplates = ITINERARY_TEMPLATES['swiss-alps'];
  }

  // If no static template exists, dynamically architect authentic days using destination famous places & activities
  if (!baseTemplates && dest) {
    const places = dest.famousPlaces || [];
    const exps = dest.experiences || [];
    const cuisine = dest.cuisine || [];

    baseTemplates = [
      {
        day: 1,
        title: `Arrival, ${places[0]?.name || destinationName} & Vistas`,
        theme: 'Acclimatization & Signature Landmarks',
        morning: {
          time: '09:00 AM – 12:00 PM',
          title: `Arrival & Exploration of ${destinationName}`,
          location: places[0]?.name || destinationName,
          category: 'Orientation & Sightseeing',
          desc: `Arrive, settle in, and take in the panoramic terrain of ${destinationName}. Discover local architecture and scenic vistas.`,
          dining: `Breakfast: Fresh regional morning specials and artisanal coffee.`,
        },
        afternoon: {
          time: '01:30 PM – 04:30 PM',
          title: places[0]?.name ? `Visit ${places[0].name}` : `Signature Landmark Discovery`,
          location: places[0]?.name || destinationName,
          category: 'Cultural Exploration',
          desc: places[0]?.desc || `Immerse yourself in authentic natural beauty and cultural heritage.`,
          dining: `Lunch: Taste local favorites like ${cuisine[0] || 'regional delicacies'}.`,
        },
        evening: {
          time: '06:00 PM – 09:00 PM',
          title: `Sunset Promenade & Gastronomy`,
          location: `${destinationName} Old Town`,
          category: 'Dining & Leisure',
          desc: `Stroll through the illuminated streets and enjoy evening ambiance.`,
          dining: `Dinner: Authentic dinner featuring ${cuisine.slice(0, 2).join(' and ') || 'curated chef specials'}.`,
        },
        insiderTip: dest.insiderTip || `Explore in early morning for peaceful light and uncrowded sights.`,
        estimatedCost: { stay: '₹6,000', food: '₹2,500', activities: '₹1,500', transport: '₹1,200' },
      },
      {
        day: 2,
        title: places[1]?.name ? `${places[1].name} & Scenic Trails` : `Natural Wonders & Heritage`,
        theme: 'Active Exploration & Iconic Highlights',
        morning: {
          time: '08:30 AM – 12:30 PM',
          title: places[1]?.name ? `Excursion to ${places[1].name}` : `Scenic Morning Excursion`,
          location: places[1]?.name || destinationName,
          category: 'Heritage & Panorama',
          desc: places[1]?.desc || `Experience iconic viewpoints and celebrated photography locations.`,
          dining: `Midday refreshment: Fresh local pastries and teas.`,
        },
        afternoon: {
          time: '02:00 PM – 05:00 PM',
          title: exps[0] || `Curated Local Activity`,
          location: destinationName,
          category: 'Adventure & Immersion',
          desc: exps[0] ? `Enjoy: ${exps[0]}` : `Explore off-the-beaten-path trails and local artisan workshops.`,
          dining: `Afternoon tea and regional sweets.`,
        },
        evening: {
          time: '06:30 PM – 09:30 PM',
          title: `Twilight Viewpoint & Local Dining`,
          location: destinationName,
          category: 'Gastronomy',
          desc: `Relax as twilight falls over the horizon and sample regional signature dishes.`,
          dining: `Dinner: Regional tasting menu at a top-rated establishment.`,
        },
        insiderTip: `Wear broken-in comfortable footwear and carry sunglasses and a light jacket.`,
        estimatedCost: { stay: '₹6,000', food: '₹2,800', activities: '₹2,200', transport: '₹1,400' },
      },
      {
        day: 3,
        title: places[2]?.name ? `${places[2].name} & Hidden Gems` : `Traditions & Artisan Culture`,
        theme: 'Local Immersion & Panoramic Views',
        morning: {
          time: '09:00 AM – 12:00 PM',
          title: places[2]?.name ? `Discover ${places[2].name}` : `Morning Exploration`,
          location: places[2]?.name || destinationName,
          category: 'Cultural Discovery',
          desc: places[2]?.desc || `Explore unique cultural topography and iconic architectural marvels.`,
          dining: `Brunch: Artisan farm-to-table breakfast.`,
        },
        afternoon: {
          time: '01:30 PM – 04:30 PM',
          title: exps[1] || `Local Experience & Craft Trails`,
          location: destinationName,
          category: 'Culture & Nature',
          desc: exps[1] ? `Experience: ${exps[1]}` : `Visit local markets and engage with master craftspeople.`,
          dining: `Sample street delicacies and artisanal desserts.`,
        },
        evening: {
          time: '06:00 PM – 09:00 PM',
          title: `Celebratory Farewell Dinner`,
          location: destinationName,
          category: 'Gastronomy',
          desc: `Commemorate your trip with a memorable dinner overlooking scenic vistas.`,
          dining: `Dinner: Signature specialties like ${cuisine[2] || cuisine[0] || 'local specialties'}.`,
        },
        insiderTip: dest.insiderTip || `Book popular viewpoints and restaurants in advance.`,
        estimatedCost: { stay: '₹6,000', food: '₹3,000', activities: '₹2,000', transport: '₹1,500' },
      },
      {
        day: 4,
        title: places[3]?.name ? `${places[3].name} & Farewell` : `Memories & Scenic Departures`,
        theme: 'Reflection, Souvenirs & Departure',
        morning: {
          time: '09:30 AM – 12:00 PM',
          title: places[3]?.name ? `Visit ${places[3].name}` : `Final Morning Sightseeing`,
          location: places[3]?.name || destinationName,
          category: 'Sightseeing',
          desc: places[3]?.desc || `Soak in final tranquil morning moments before preparation for departure.`,
          dining: `Leisurely farewell breakfast with scenic views.`,
        },
        afternoon: {
          time: '01:00 PM – 03:30 PM',
          title: `Market Souvenirs & Artisan Shopping`,
          location: `${destinationName} Bazaars`,
          category: 'Shopping & Leisure',
          desc: `Pick up authentic handcrafted mementos and artisanal local goods.`,
          dining: `Casual cafe lunch with light refreshments.`,
        },
        evening: {
          time: '04:30 PM – 07:00 PM',
          title: `Onward Departure with Cherished Memories`,
          location: `Airport / Station`,
          category: 'Departure',
          desc: `Transfer to transit terminal carrying unforgettable memories of ${destinationName}.`,
          dining: `Transit snack and farewell refreshment.`,
        },
        insiderTip: `Keep digital copies of boarding passes and transit bookings on your mobile.`,
        estimatedCost: { stay: '₹4,500', food: '₹2,000', activities: '₹1,000', transport: '₹1,800' },
      },
    ];
  }

  if (!baseTemplates) {
    baseTemplates = ITINERARY_TEMPLATES.manali;
  }

  const days = [];

  for (let i = 0; i < durationDays; i++) {
    const templateIndex = i % baseTemplates.length;
    const baseDay = baseTemplates[templateIndex];

    days.push({
      day: i + 1,
      title: i < baseTemplates.length ? baseDay.title : `Day ${i + 1}: Hidden Discoveries & Scenic Exploration`,
      theme: baseDay.theme,
      morning: { ...baseDay.morning, isCompleted: false },
      afternoon: { ...baseDay.afternoon, isCompleted: false },
      evening: { ...baseDay.evening, isCompleted: false },
      insiderTip: baseDay.insiderTip,
      estimatedCost: {
        stay: baseDay.estimatedCost?.stay || '₹5,000',
        food: baseDay.estimatedCost?.food || '₹2,000',
        activities: baseDay.estimatedCost?.activities || '₹1,500',
        transport: baseDay.estimatedCost?.transport || '₹1,200',
      },
      notes: '',
    });
  }

  return {
    id: `dk-itinerary-${destinationId}-${Date.now()}`,
    destinationId,
    destinationName,
    durationDays,
    travelStyle,
    budgetTier,
    groupType,
    createdAt: new Date().toISOString(),
    days,
  };
}
